#   Data Analytics Project - การวิเคราะห์การต่อสัญญาการใช้บริการของลูกค้า

### Setup

In [1]:
import pandas as pd
import numpy as np

### Data Collection

In [2]:
df = pd.read_csv("telco_cleaned.csv", encoding='UTF-8')

In [3]:
df.head()

,customer_id,gender,age,under_30,senior_citizen,married,dependents,number_of_dependents,city,zip_code,...,total_charges,total_refunds,total_extra_data_charges,total_long_distance_charges,total_revenue,satisfaction_score,customer_status,churn_label,churn_score,cltv
0,8779-QRDMV,Male,78,No,Yes,No,No,0,Los Angeles,90022,...,39.65,0.00,20,0.00,59.65,3,Churned,Yes,91,5433
1,7495-OOKFY,Female,74,No,Yes,Yes,Yes,1,Los Angeles,90063,...,633.30,0.00,0,390.80,1024.10,3,Churned,Yes,69,5302
2,1658-BYGOY,Male,71,No,Yes,No,Yes,3,Los Angeles,90065,...,1752.55,45.61,0,203.94,1910.88,2,Churned,Yes,81,3179
3,4598-XLKNJ,Female,78,No,Yes,Yes,Yes,1,Inglewood,90303,...,2514.50,13.43,0,494.00,2995.07,2,Churned,Yes,88,5337
4,4846-WHAFZ,Female,80,No,Yes,Yes,Yes,1,Whittier,90602,...,2868.15,0.00,0,234.21,3102.36,2,Churned,Yes,67,2793

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6589 entries, 0 to 6588
Data columns (total 43 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   customer_id                        6589 non-null   object
 1   gender                             6589 non-null   object
 2   age                                6589 non-null   int64
 3   under_30                           6589 non-null   object
 4   senior_citizen                     6589 non-null   object
 5   married                            6589 non-null   object
 6   dependents                         6589 non-null   object
 7   number_of_dependents               6589 non-null   int64
 8   city                               6589 non-null   object
 9   zip_code                           6589 non-null   int64
 10  population                         6589 non-null   int64
 11  referred_a_friend                  6589 non-null   object
 12  number_of_referrals                6589 non-null   int64
 13  tenure_in_months                   6589 non-null   int64
 14  offer                              6589 non-null   object
 15  phone_service                      6589 non-null   object
 16  avg_monthly_long_distance_charges  6589 non-null   float64
 17  multiple_lines                     6589 non-null   object
 18  internet_service                   6589 non-null   object
 19  internet_type                      6589 non-null   object
 20  avg_monthly_gb_download            6589 non-null   int64
 21  online_security                    6589 non-null   object
 22  online_backup                      6589 non-null   object
 23  device_protection_plan             6589 non-null   object
 24  premium_tech_support               6589 non-null   object
 25  streaming_tv                       6589 non-null   object
 26  streaming_movies                   6589 non-null   object
 27  streaming_music                    6589 non-null   object
 28  unlimited_data                     6589 non-null   object
 29  contract                           6589 non-null   object
 30  paperless_billing                  6589 non-null   object
 31  payment_method                     6589 non-null   object
 32  monthly_charge                     6589 non-null   float64
 33  total_charges                      6589 non-null   float64
 34  total_refunds                      6589 non-null   float64
 35  total_extra_data_charges           6589 non-null   int64
 36  total_long_distance_charges        6589 non-null   float64
 37  total_revenue                      6589 non-null   float64
 38  satisfaction_score                 6589 non-null   int64
 39  customer_status                    6589 non-null   object
 40  churn_label                        6589 non-null   object
 41  churn_score                        6589 non-null   int64
 42  cltv                               6589 non-null   int64
dtypes: float64(6), int64(11), object(26)
memory usage: 2.2+ MB

In [5]:
df.describe()

,age,number_of_dependents,zip_code,population,number_of_referrals,tenure_in_months,avg_monthly_long_distance_charges,avg_monthly_gb_download,monthly_charge,total_charges,total_refunds,total_extra_data_charges,total_long_distance_charges,total_revenue,satisfaction_score,churn_score,cltv
count,6589.000000,6589.000000,6589.000000,6589.000000,6589.000000,6589.000000,6589.000000,6589.000000,6589.000000,6589.000000,6589.000000,6589.000000,6589.000000,6589.000000,6589.000000,6589.000000,6589.000000
mean,46.760510,0.476097,93491.504477,22116.481105,2.020944,34.499772,23.004277,20.876461,66.228472,2432.042243,2.080938,7.169525,798.087251,3235.218082,3.194718,59.191228,4422.180756
std,16.841362,0.968499,1857.575392,21217.958517,3.024016,23.968734,15.466844,20.406247,29.907382,2265.500080,8.125054,25.803163,853.767972,2854.600036,1.207720,21.231782,1179.656518
min,19.000000,0.000000,90001.000000,11.000000,0.000000,1.000000,0.000000,0.000000,18.250000,18.850000,0.000000,0.000000,0.000000,21.610000,1.000000,5.000000,2003.000000
25%,33.000000,0.000000,92103.000000,2271.000000,0.000000,12.000000,9.250000,4.000000,40.550000,544.550000,0.000000,0.000000,106.680000,835.450000,3.000000,41.000000,3513.000000
50%,46.000000,0.000000,93526.000000,17372.000000,0.000000,32.000000,22.920000,17.000000,72.850000,1563.900000,0.000000,0.000000,472.680000,2376.450000,3.000000,63.000000,4552.000000
75%,60.000000,0.000000,95333.000000,36149.000000,3.000000,57.000000,36.440000,27.000000,90.600000,4003.000000,0.000000,0.000000,1275.120000,5106.640000,4.000000,76.000000,5393.000000
max,80.000000,9.000000,96150.000000,105285.000000,11.000000,72.000000,49.990000,85.000000,118.750000,8684.800000,49.790000,150.000000,3564.720000,11979.340000,5.000000,96.000000,6500.000000

### Data Cleaning

### Data Processing

In [6]:
df.head(5)

,customer_id,gender,age,under_30,senior_citizen,married,dependents,number_of_dependents,city,zip_code,...,total_charges,total_refunds,total_extra_data_charges,total_long_distance_charges,total_revenue,satisfaction_score,customer_status,churn_label,churn_score,cltv
0,8779-QRDMV,Male,78,No,Yes,No,No,0,Los Angeles,90022,...,39.65,0.00,20,0.00,59.65,3,Churned,Yes,91,5433
1,7495-OOKFY,Female,74,No,Yes,Yes,Yes,1,Los Angeles,90063,...,633.30,0.00,0,390.80,1024.10,3,Churned,Yes,69,5302
2,1658-BYGOY,Male,71,No,Yes,No,Yes,3,Los Angeles,90065,...,1752.55,45.61,0,203.94,1910.88,2,Churned,Yes,81,3179
3,4598-XLKNJ,Female,78,No,Yes,Yes,Yes,1,Inglewood,90303,...,2514.50,13.43,0,494.00,2995.07,2,Churned,Yes,88,5337
4,4846-WHAFZ,Female,80,No,Yes,Yes,Yes,1,Whittier,90602,...,2868.15,0.00,0,234.21,3102.36,2,Churned,Yes,67,2793

##### Ordinal Encoding

columns: under_30, senior_citizen, married, dependents, referred_a_friend, phone_service, multiple_lines, internet_service, online_security, online_backup, 
         device_protection_plan, premium_tech_support, streaming_tv, streaming_movies, streaming_music, unlimited_data, paperless_billing, churn_label

In [24]:
select_columns = ['under_30', 'senior_citizen', 'married', 'dependents', 'referred_a_friend', 
                  'phone_service', 'multiple_lines', 'internet_service', 'online_security', 'online_backup', 
                  'device_protection_plan', 'premium_tech_support', 'streaming_tv', 'streaming_movies', 'streaming_music', 
                  'unlimited_data', 'paperless_billing', 'churn_label']
oe_df = pd.DataFrame()
for i in select_columns:
    oe_df[i + '_oe'] = df[i].str.strip().str.lower().map({'yes': 1, 'no': 0})
oe_df.head()

,under_30_oe,senior_citizen_oe,married_oe,dependents_oe,referred_a_friend_oe,phone_service_oe,multiple_lines_oe,internet_service_oe,online_security_oe,online_backup_oe,device_protection_plan_oe,premium_tech_support_oe,streaming_tv_oe,streaming_movies_oe,streaming_music_oe,unlimited_data_oe,paperless_billing_oe,churn_label_oe
0,0,1,0,0,0,0,0,1,0,0,1,0,0,1,0,0,1,1
1,0,1,1,1,1,1,1,1,0,1,0,0,0,0,0,1,1,1
2,0,1,0,1,0,1,1,1,0,0,0,0,1,1,1,1,1,1
3,0,1,1,1,1,1,0,1,0,1,1,0,1,1,0,1,1,1
4,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,1,1,1

##### One-Hot Encoding (ONE)

columns : gender, offer, internet_type, contract, payment_method, customer_status

In [13]:
gender_df = pd.concat([df['gender'], pd.get_dummies(df['gender'], dtype=int)], axis=1)
gender_df.head()

   gender  Female  Male
0    Male       0     1
1  Female       1     0
2    Male       0     1
3  Female       1     0
4  Female       1     0

In [14]:
offer_df = pd.concat([df['offer'], pd.get_dummies(df['offer'], dtype=int)], axis=1)
offer_df.head()

      offer  No Offer  Offer A  Offer B  Offer C  Offer D  Offer E
0  No Offer         1        0        0        0        0        0
1   Offer E         0        0        0        0        0        1
2   Offer D         0        0        0        0        1        0
3   Offer C         0        0        0        1        0        0
4   Offer C         0        0        0        1        0        0

In [15]:
internet_type_df = pd.concat([df['internet_type'], pd.get_dummies(df['internet_type'], dtype=int)], axis=1)
internet_type_df.head()

  internet_type  Cable  DSL  Fiber Optic  No Internet
0           DSL      0    1            0            0
1   Fiber Optic      0    0            1            0
2   Fiber Optic      0    0            1            0
3   Fiber Optic      0    0            1            0
4   Fiber Optic      0    0            1            0

In [17]:
contract_df = pd.concat([df['contract'], pd.get_dummies(df['contract'], dtype=int)], axis=1)
contract_df.head()

         contract  Month-to-Month  One Year  Two Year
0  Month-to-Month               1         0         0
1  Month-to-Month               1         0         0
2  Month-to-Month               1         0         0
3  Month-to-Month               1         0         0
4  Month-to-Month               1         0         0

In [18]:
payment_method_df = pd.concat([df['payment_method'], pd.get_dummies(df['payment_method'], dtype=int)], axis=1)
payment_method_df.head()

    payment_method  Bank Withdrawal  Credit Card  Mailed Check
0  Bank Withdrawal                1            0             0
1      Credit Card                0            1             0
2  Bank Withdrawal                1            0             0
3  Bank Withdrawal                1            0             0
4  Bank Withdrawal                1            0             0

In [19]:
customer_status_df = pd.concat([df['customer_status'], pd.get_dummies(df['customer_status'], dtype=int)], axis=1)
customer_status_df.head()

  customer_status  Churned  Stayed
0         Churned        1       0
1         Churned        1       0
2         Churned        1       0
3         Churned        1       0
4         Churned        1       0

#### Target Encoding

### Data Exploration

### Data Modeling

### Data Deployment